CREATE table email
(
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    type           tinyint(4) NOT NULL DEFAULT 0,
    group_id       INTEGER       NOT NULL DEFAULT 0,
    subject        varchar(1000) NOT NULL DEFAULT '',
    reply_to       json,
    from_name      varchar(50)   NOT NULL DEFAULT '',
    from_address   varchar(150)  NOT NULL DEFAULT '',
    `to`           json,
    bcc            json,
    cc             json,
    `text`         text,
    html           text,
    sender         json,
    attachments    json ,
    spf_check      tinyint(1) DEFAULT 0 ,
    dkim_check     tinyint(1) DEFAULT 0 ,
    status         tinyint(4) NOT NULL DEFAULT 0 ,
    send_user_id   int unsigned NOT NULL DEFAULT 0 ,
    is_read        tinyint(1) NOT NULL DEFAULT 0 ,
    error          text ,
    cron_send_time datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    send_date      datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    create_time    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    update_time    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP
)